### ISSUE TITLE
Importing whole (personal) channel fails

### ISSUE THREAD

**Issue by dadaurs** [cfelipe/newsboat-url-generator#1]
Running `python newsboat-urls-generator.py -i <channel_id> -v` fails with
```
Traceback (most recent call last):
  File "newsboat-urls-generator.py", line 84, in <module>
    main()
  File "newsboat-urls-generator.py", line 18, in main
    generate_list(feed_url, args)
  File "newsboat-urls-generator.py", line 41, in generate_list
    for channel in channel_list['items']:
KeyError: 'items'
```

Running on a single channel url works though.

This is on arch linux using python 3.8.3, but I get the same error on gentoo with python 3.7.8.

**Comment by felipos** [comment]
dadaurs, 

Thank you for reporting. It seems the API key I've put into this script got too many traffic. I wrote this script just for a couple of friends and didn't expect other people would use it.

Anyway, there is nothing I can do in this case. I updated the README.md with the new requirement.
